#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# i3 dir
idir="$HOME/.config/i3"

# Export desktop session
export XDG_CURRENT_DESKTOP='i3'

# Kill already running process
_ps=(xsettingsd ksuperkey)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Lauch xsettingsd daemon
xsettingsd --config="$idir"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Enable power management
xfce4-power-manager &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
"$idir"/themes/wallpaper.sh

# Lauch notification daemon
"$idir"/scripts/i3_dunst

# Lauch polybar
"$idir"/scripts/i3_bar

# Lauch compositor
"$idir"/scripts/i3_comp


exec sh -c 'sudo systemctl restart sddm' &

exec sh -c 'pgrep -x spotify > /dev/null || exec spotify' &

# Start Alacritty on workspace 2 if not already running
exec sh -c 'pgrep -x alacritty > /dev/null || (i3-msg workspace 2; exec ~/.config/i3/scripts/i3_term)' &

# Start Firefox on workspace 1 if not already running
exec sh -c 'pgrep -x firefox > /dev/null || (sleep 1; i3-msg workspace 1; exec zen-browser)' &

exec sh -c 'exec /home/jachym/beeper/*' &


# Start mpd
exec mpd &

# Keyboard layout
exec setxkbmap -layout us,cz -variant ,qwerty -option caps:escape,grp:alt_shift_toggle,grp:switch &

xautolock -time 10 -locker "systemctl suspend && betterlockscreen -l" &
xautolock -time 25 -locker "systemctl hybernate && betterlockscreen -l" &
